In [1]:
import pandas as pd

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [5]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df.fillna("ved")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,ved,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,ved,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,ved,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,ved,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,ved,1,2,W./C. 6607,23.4500,ved,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,ved,Q

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df.set_index("Name", inplace = True) # name is treated as index

In [10]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
df.reset_index(inplace = True)

In [12]:
df

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
df.drop('PassengerId',axis = 1, inplace = True)

In [14]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
g= df.groupby('Survived')

In [16]:
g

In [17]:
g.sum()

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Survived,,,,,,,,,,
0,"Braund, Mr. Owen HarrisAllen, Mr. William Henr...",1390,malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,A/5 2117137345033087717463349909A/5. 215134708...,12142.7199,E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...,SSQSSSSSQSSSCSSCSCSSSSSCSQCSSSCCSCSSCSSSSSCSSS...
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",667,femalefemalefemalefemalefemalefemalefemalefema...,8219.67,162,159,PC 17599STON/O2. 3101282113803347742237736PP 9...,16551.2294,C85C123G6C103D56A6B78D33C52B28F33C23 C25 C27D1...,CSSSCSSSSCSQSSQCQCCCQQCSSSSCSSSSSSQSSSCSSSQSCS...

In [19]:
g.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [20]:
g.mean(numeric_only=True)

            Pclass        Age     SibSp     Parch       Fare
Survived
0         2.531876  30.626179  0.553734  0.329690  22.117887
1         1.950292  28.343690  0.473684  0.464912  48.395408

In [21]:
g1 = df.groupby('Pclass')

In [23]:
g1.sum(numeric_only=True)

        Survived      Age  SibSp  Parch        Fare
Pclass
1            136  7111.42     90     77  18177.4125
2             87  5168.83     74     70   3801.8417
3            119  8924.92    302    193   6714.6951

In [24]:
g1.mean(numeric_only=True)

        Survived        Age     SibSp     Parch       Fare
Pclass
1       0.629630  38.233441  0.416667  0.356481  84.154687
2       0.472826  29.877630  0.402174  0.380435  20.662183
3       0.242363  25.140620  0.615071  0.393075  13.675550

In [29]:
g1.max(numeric_only=True)

        Survived   Age  SibSp  Parch      Fare
Pclass
1              1  80.0      3      4  512.3292
2              1  70.0      3      3   73.5000
3              1  74.0      8      6   69.5500

In [30]:
idx = df.groupby('Pclass')['Fare'].idxmax()
df.loc[idx, ['Pclass', 'Name', 'Fare']]

     Pclass                        Name      Fare
258       1            Ward, Miss. Anna  512.3292
72        2        Hood, Mr. Ambrose Jr   73.5000
159       3  Sage, Master. Thomas Henry   69.5500

In [32]:
g1.max(numeric_only=True).T   # Transpose

Pclass           1     2      3
Survived    1.0000   1.0   1.00
Age        80.0000  70.0  74.00
SibSp       3.0000   3.0   8.00
Parch       4.0000   3.0   6.00
Fare      512.3292  73.5  69.55

In [33]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [35]:
df5 = df[['Name','Survived' , 'Pclass']][0:5]

In [37]:
df6 = df[['Name','Survived' , 'Pclass']][5:10]

In [38]:
df5

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3

In [39]:
df6

                                                Name  Survived  Pclass
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [40]:
pd.concat([df5,df6])

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [44]:
df7 = pd.concat([df5,df6], axis = 1) # axis = 1 so join column wise
df7

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Braund, Mr. Owen Harris",0.0,3.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",1.0,3.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1.0,1.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",0.0,3.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",0.0,3.0
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",0.0,1.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",0.0,3.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,3.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,2.0

In [43]:
df7.fillna("ved")

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Braund, Mr. Owen Harris",0.0,3.0,ved,ved,ved
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,ved,ved,ved
2,"Heikkinen, Miss. Laina",1.0,3.0,ved,ved,ved
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1.0,1.0,ved,ved,ved
4,"Allen, Mr. William Henry",0.0,3.0,ved,ved,ved
5,ved,ved,ved,"Moran, Mr. James",0.0,3.0
6,ved,ved,ved,"McCarthy, Mr. Timothy J",0.0,1.0
7,ved,ved,ved,"Palsson, Master. Gosta Leonard",0.0,3.0
8,ved,ved,ved,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,3.0
9,ved,ved,ved,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,2.0

In [51]:
data1 = pd.DataFrame({
    'Key1' : [3,4,5,6,7],
    'Key2' : [6,6,5,6,7],
    'Key3' : [8,49,5,6,7],
})

data1

   Key1  Key2  Key3
0     3     6     8
1     4     6    49
2     5     5     5
3     6     6     6
4     7     7     7

In [50]:
data2 = pd.DataFrame({
    'Key1' : [3,54,5,76,87],
    'Key4' : [6,63,5,56,7],
    'Key5' : [58,449,5,556,57],
})

data2

   Key1  Key4  Key5
0     3     6    58
1    54    63   449
2     5     5     5
3    76    56   556
4    87     7    57

In [52]:
pd.merge(data1,data2) #An inner merge (also called inner join) means:👉 Keep only the common (matching) rows from both datasets

   Key1  Key2  Key3  Key4  Key5
0     3     6     8     6    58
1     5     5     5     5     5

In [53]:
pd.merge(data1,data2,how = 'left')

   Key1  Key2  Key3  Key4  Key5
0     3     6     8   6.0  58.0
1     4     6    49   NaN   NaN
2     5     5     5   5.0   5.0
3     6     6     6   NaN   NaN
4     7     7     7   NaN   NaN

In [54]:
pd.merge(data1,data2,how = 'right')

   Key1  Key2  Key3  Key4  Key5
0     3   6.0   8.0     6    58
1    54   NaN   NaN    63   449
2     5   5.0   5.0     5     5
3    76   NaN   NaN    56   556
4    87   NaN   NaN     7    57

In [55]:
pd.merge(data1,data2,how = 'cross')

    Key1_x  Key2  Key3  Key1_y  Key4  Key5
0        3     6     8       3     6    58
1        3     6     8      54    63   449
2        3     6     8       5     5     5
3        3     6     8      76    56   556
4        3     6     8      87     7    57
5        4     6    49       3     6    58
6        4     6    49      54    63   449
7        4     6    49       5     5     5
8        4     6    49      76    56   556
9        4     6    49      87     7    57
10       5     5     5       3     6    58
11       5     5     5      54    63   449
12       5     5     5       5     5     5
13       5     5     5      76    56   556
14       5     5     5      87     7    57
15       6     6     6       3     6    58
16       6     6     6      54    63   449
17       6     6     6       5     5     5
18       6     6     6      76    56   556
19       6     6     6      87     7    57
20       7     7     7       3     6    58
21       7     7     7      54    63   449
22       7     7     7       5     5     5
23       7     7     7      76    56   556
24       7     7     7      87     7    57

In [59]:
pd.merge(data1,data2,how = 'outer' ,on = 'Key1')

   Key1  Key2  Key3  Key4   Key5
0     3   6.0   8.0   6.0   58.0
1     4   6.0  49.0   NaN    NaN
2     5   5.0   5.0   5.0    5.0
3     6   6.0   6.0   NaN    NaN
4     7   7.0   7.0   NaN    NaN
5    54   NaN   NaN  63.0  449.0
6    76   NaN   NaN  56.0  556.0
7    87   NaN   NaN   7.0   57.0

In [60]:
import pandas as pd  # 👉 .join() works on index, not on columns like merge()

data1 = {'Name': ['A', 'B', 'C']}
data2 = {'Marks': [80, 90, 70]}

df1 = pd.DataFrame(data1, index=['a', 'b', 'c'])
df2 = pd.DataFrame(data2, index=['b', 'c', 'd'])

df1.join(df2, how='right')

  Name  Marks
b    B     80
c    C     90
d  NaN     70

In [61]:
df1.join(df2, how='inner')

  Name  Marks
b    B     80
c    C     90

In [62]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
df['Fare_INR'] = df['Fare'].apply(lambda x: x * 83)  # Using .apply() to create new column

In [64]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,601.7500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5916.5139
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,657.7750
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,4407.3000
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,668.1500

In [67]:
def convert_to_inr(x):
    return x * 83
df['Fare_INR'] = df['Fare'].apply(convert_to_inr)

In [68]:
df['Fare_INR']

0       601.7500
1      5916.5139
2       657.7750
3      4407.3000
4       668.1500
         ...
886    1079.0000
887    2490.0000
888    1946.3500
889    2490.0000
890     643.2500
Name: Fare_INR, Length: 891, dtype: float64

In [69]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,601.7500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5916.5139
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,657.7750
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,4407.3000
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,668.1500
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,1079.0000
887,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,2490.0000
888,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1946.3500
889,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,2490.0000
890,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,643.2500

In [71]:
df['name_len'] = df['Name'].apply(len)

In [72]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,name_len
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,601.7500,23
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5916.5139,51
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,657.7750,22
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,4407.3000,44
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,668.1500,24

In [73]:
def fare_category(x):
    if x < 10:
        return 'cheap'
    elif 10 <= x <= 20:
        return 'mid'
    else:
        return 'high'

df['category'] = df['Fare'].apply(fare_category)

In [74]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,name_len,category
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,601.7500,23,cheap
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5916.5139,51,high
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,657.7750,22,cheap
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,4407.3000,44,high
4,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,668.1500,24,cheap